### ISSUE TITLE
algorithm code in R

### ISSUE THREAD

**Issue by profiack** [kyrcha/ama#3]
Dear sir

First of all, I want to congratulate you on the article "Data Outlier Detection using the Chebyshev Theorem - Paper review and online adaptation".
My name is Cléber Iack, Brazilian. I would like to ask for your help. 
Do you have the implementation of the algorithm code in R (Chebyshev's inequality an Outlier Detection Value (ODV))?
Thanks for considering my request.

**Comment by kyrcha** [comment]
Hi @profiack 
I'm glad you liked the article. Unfortunately, I don't have an implementation in R but I have: 
- one in [Python](https://github.com/kyrcha/NAB/blob/master/nab/detectors/chebyshev/chebyshev_detector.py)
- one in [Lua](https://gist.github.com/kyrcha/974f662d988906023d20cadf22a8a88e) (more complex since it runs on Redis)

the first one would be easier to convert to R. Give it a try and if your have any troubles let me know.
